### ISSUE TITLE
Question about the redzone size.

### ISSUE THREAD

**Issue by Marsman1996** [purdue-secomp-lab/MEDS#4]
Hi, 

If I do not misunderstand the paper, the size of the MEDS redzone should be 4MB. But in the example below the redzone size seems much smaller than 4MB.

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(){
    char *a = malloc(0x20);
    char *b = malloc(0x20);
    // char *a = malloc(0x1000000);
    // char *b = malloc(0x1000000);
    int offset = 0x4030;
    printf("a = %p, b = %p\n", a, b);
    printf("writing in %p\n", &a[offset]);
    a[offset] = 'a';
    free(a);
    free(b);
    return 0;
}
```

And the outout is:
```
a = 0x42e90657d010, b = 0x42e906581040
```
So the redzone size is about 16KB(`0x42e906581040 - 0x42e90657d010 - 0x20 = 0x4010`).

Thanks for any reply!

**Comment by whhan** [comment]
Sorry for my late reply. Thank you for finding this issue! However, I have some urgent tasks. I can look into this issue at the end of this month.

**Comment by whhan** [comment]
Could you let me know the exact compile command you used? I could get the following result from your test code.

```
root@8e1e6d9d2355:/src# clang -fsanitize=meds -mllvm -meds-stack=1 -mllvm -meds-global=1 -mcmodel=large -Wl,--emit-relocs a.c
root@8e1e6d9d2355:/src# ./a.out
a = 0x4204af101010, b = 0x4204af105040
writing in 0x4204af101040
=================================================================
==185==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x4204af101040 at pc 0x0000004f60ac bp 0x7fffdd206850 sp 0x7fffdd206848
WRITE of size 1 at 0x4204af101040 thread T0
    #0 0x4f60ab in main (/src/a.out+0x4f60ab)
    #1 0x7f04af47683f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #2 0x4199c8 in _start (/src/a.out+0x4199c8)

Address 0x4204af101040 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow (/src/a.out+0x4f60ab) in main
Shadow bytes around the buggy address:
  0x084115e181b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x084115e181c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x084115e181d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x084115e181e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x084115e181f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x084115e18200: fa fa 00 00 00 00 fa fa[fa]fa fa fa fa fa fa fa
  0x084115e18210: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x084115e18220: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x084115e18230: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x084115e18240: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x084115e18250: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==185==ABORTING

```

**Comment by Marsman1996** [comment]
Yes, the test code could trigger the MEDS, but my question is about the redzone size.
Taking your output as an example, the redzone size seems to be 16KB (0x4204af105040-0x4204af101010-0x20= 0x4010), not 4MB.
To bypass the MEDS, you could change the `offset` to 0x4030 as I edited.
